### ISSUE TITLE
Support common dice

### ISSUE THREAD

**Issue by Jean1995** [DimensionalScoop/roll-by-mail#1]
The bot is really nice. Unfortunately, I can not simulate my lovely d9223372036854775808.

**Comment by DimensionalScoop** [comment]
Thanks! This is unfortunately a backend issue: Numpy only supports ctypes. I switched from `int64` to `uint64`, so `d9223372036854775808` should be supported now. However, underlying issue still exists, roll-by-mail will never support dice with an arbitrary number of dice.

**Comment by Jean1995** [comment]
Perfect! Works like a charm now.
